version: "3.8"
services:
  firefox:
    container_name: firefox
    environment:
      - PUID=1029
      - PGID=100
      - TZ=Europe/Paris
      - LSIO_FIRST_PARTY=true
      - NVIDIA_DRIVER_CAPABILITIES=graphics,compat32,utility
      - PULSE_RUNTIME_PATH=/defaults
    volumes:
      - /volume2/dockerssd/firefox:/config
    restart: always
    network_mode: container:gluetun
    image: lscr.io/linuxserver/firefox:1147.0.3
networks: {}


