version: "3.8"
services:
  firefox:
    container_name: firefox
    ports:
      - 5812:3000
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
      - LSIO_FIRST_PARTY=true
      - NVIDIA_DRIVER_CAPABILITIES=graphics,compat32,utility
      - PULSE_RUNTIME_PATH=/defaults
    volumes:
      - /volume2/dockerssd/firefox:/config
    restart: always
    image: lscr.io/linuxserver/firefox:latest
networks: {}
