version: "3.2"
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:0.53.3
    container_name: changedetection
    hostname: changedetection
    volumes:
      - /volume2/dockerssd/changedetection/data:/datastore
    # Comment out ports: when using behind a reverse proxy , enable networks: etc.
    ports:
      - 5050:5000
    restart: unless-stopped
  # Used for fetching pages via WebDriver+Chrome where you need Javascript support.
  # Now working on arm64 (needs testing on rPi - tested on Oracle ARM instance)
  # replace image with seleniarm/standalone-chromium:4.0.0-20211213

  # If WEBDRIVER or PLAYWRIGHT are enabled, changedetection container depends on that
  # and must wait before starting (substitute "browser-chrome" with "playwright-chrome" if last one is used)
  #    depends_on:
  #        browser-chrome:
  #            condition: service_started

  # Used for fetching pages via Playwright+Chrome where you need Javascript support.
  # RECOMMENDED FOR FETCHING PAGES WITH CHROME
  #    playwright-chrome:
  #        hostname: playwright-chrome
  #        image: dgtlmoon/sockpuppetbrowser:latest
  #        cap_add:
  #            - SYS_ADMIN
  ## SYS_ADMIN might be too much, but it can be needed on your platform https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-gitlabci
  #        restart: unless-stopped
  #        environment:
  #            - SCREEN_WIDTH=1920
  #            - SCREEN_HEIGHT=1024
  #            - SCREEN_DEPTH=16
  #            - MAX_CONCURRENT_CHROME_PROCESSES=10

  # Used for fetching pages via Playwright+Chrome where you need Javascript support.
  # Note: Works well but is deprecated, does not fetch full page screenshots (doesnt work with Visual Selector)
  #       Does not report status codes (200, 404, 403) and other issues
  #    browser-chrome:
  #        hostname: browser-chrome
  #        image: selenium/standalone-chrome:4
  #        environment:
  #            - VNC_NO_PASSWORD=1
  #            - SCREEN_WIDTH=1920
  #            - SCREEN_HEIGHT=1080
  #            - SCREEN_DEPTH=24
  #        volumes:
  #            # Workaround to avoid the browser crashing inside a docker container
  #            # See https://github.com/SeleniumHQ/docker-selenium#quick-start
  #            - /dev/shm:/dev/shm
  #        restart: unless-stopped

volumes:
  changedetection-data: null
networks: {}

