version: "3.8"
services:
  filebrowser:
    container_name: filebrowser
    ports:
      - 8147:8080
    environment:
      - TZ=Europe/Paris
      - PUID=1029
      - PGID=100
    volumes:
      - /volume1:/srv
      - /volume2/dockerssd/filebrowser/config:/database
      - /volume2/dockerssd/filebrowser/config:/config
    restart: always
    image: filebrowser/filebrowser:v2.42.5
networks: {}



