version: "3.8"
services:
  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "ghcr.io/jokob-sk/netalertx-dev:latest" 
    image: ghcr.io/jokob-sk/netalertx:25.3.1
    network_mode: host
    restart: unless-stopped
    volumes:
      - /volume2/dockerssd/netalertx/config:/app/config
      - /volume2/dockerssd/netalertx/db:/app/db
      - /volume2/dockerssd/netalertx/log:/app/log
    environment:
      - TZ=Europe/Paris
      - PORT=20211
