version: "3.8"
services:
  jellyseerr:
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /volume2/dockerssd/jellyseer:/app/config
    restart: always
    image: fallenbagel/jellyseerr:2.7.3
networks: {}
