version: "3.8"
services:
  navidrome:
    container_name: navidrome
    ports:
      - 4533:4533
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /volume2/dockerssd/navidrome:/data
      - /volume1/data/media/music:/music
    restart: always
    image: deluan/navidrome:0.60.0
networks: {}



