version: "3.8"
services:
  db:
    image: postgres:15
    volumes:
      - /volume2/dockerssd/joplin:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    image: joplin/server:3.5.2
    depends_on:
      - db
    ports:
      - 22300:22300
    restart: unless-stopped
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=https://notes.antoinedelia.fr
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - MAILER_ENABLED=1
      - MAILER_HOST=smtp.gmail.com
      - MAILER_PORT=587
      - MAILER_SECURITY=starttls
      - MAILER_AUTH_USER=${MAILER_AUTH_USER}
      - MAILER_AUTH_PASSWORD=${MAILER_AUTH_PASSWORD}
      - MAILER_NOREPLY_NAME=JoplinServer
      - MAILER_NOREPLY_EMAIL=${MAILER_NOREPLY_EMAIL}
networks: {}


