version: "3.8"
services:
  jellyfin:
    container_name: jellyfin
    ports:
      - 8096:8096
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
      - JELLYFIN_PublishedServerUrl=https://media.antoinedelia.fr
    volumes:
      - /volume1/media:/media
      - /volume2/dockerssd/jellyfin:/config
    restart: always
    image: lscr.io/linuxserver/jellyfin:10.11.6
networks: {}
