version: "3.8"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.10.1
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.antoinedelia.fr,192.168.1.22:3000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    ports:
      - 3000:3000
    volumes:
      - /volume2/dockerssd/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: always
networks: {}
