version: "3.8"
services:
  radarr:
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /volume2/dockerssd/radarr:/config
      - /volume1/media:/movies
      - /volume1/Downloads:/downloads
    restart: unless-stopped
    image: ghcr.io/linuxserver/radarr
networks: {}