version: "3.8"
services:
  sonarr:
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /volume2/dockerssd/sonarr:/config
      - /volume1/media:/my-media
      - /volume1/Downloads:/downloads
    restart: unless-stopped
    image: ghcr.io/linuxserver/sonarr:latest
networks: {}
