version: "3.8"
services:
  komga:
    image: gotson/komga:1.24.1
    container_name: komga
    volumes:
      - /volume2/dockerssd/komga/data:/data
      - /volume2/dockerssd/komga/config:/config
      - /volume1/data/media:/media
    ports:
      - 25600:25600
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
networks: {}
