version: "3.8"
services:
  slskd:
    image: slskd/slskd:0.24.5
    container_name: slskd
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - /volume2/dockerssd/soulseek:/app
    restart: always
    network_mode: container:gluetun
networks: {}
