services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /volume2/dockerssd/qbittorrentvpn:/config
      - /volume1/data:/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 4000M # limit runaway RAM usage
    network_mode: container:gluetun
networks: {}
