version: "3.8"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /volume2/dockerssd/qbittorrentvpn:/config
      - /volume1/Downloads:/downloads
      - /volume1/media:/mymedia
    restart: unless-stopped
    network_mode: container:gluetun
networks: {}