services:
  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6.13.6
    container_name: cross-seed
    user: 1026:100 # this must match your torrent client (cross-seed does not support using PGID and PUID)
    ports:
      - "2468:2468"
    volumes:
      - /volume2/dockerssd/cross-seed:/config
      # You will need at least one extra volume for your media drive if using https://www.cross-seed.org/docs/tutorials/linking
      - /volume1/data/torrents:/torrents
    command: daemon
    restart: unless-stopped
